apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test_backstage
  annotations:
    github.com/project-slug: jihoon15/test_backstage
spec:
  type: service
  lifecycle: unknown
  owner: guests
