apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test_backstage
  annotations:
    github.com/project-slug: jihoon15/test_backstage
    jenkins.io/job-full-name: jenkins_test_backstage
    jira.com/project-key: "TB"
    #jira/project-key: TB
spec:
  type: service
  lifecycle: unknown
  owner: guests
