apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test_backstage
  annotations:
    github.com/project-slug: jihoon15/test_backstage
    jenkins.io/job-full-name: test_backstage/jenkins_test_backstage
		jenkins.io/github-folder: 'jihoon15/test_backstage'
    jenkins.io/job-full-name: "jenkins_test_backstage"
spec:
  type: other
  lifecycle: unknown
  owner: team-a
