apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test_backstage
  annotations:
    github.com/project-slug: jihoon15/test_backstage
    jenkins.io/job-full-name: test_bs_CI
    # jira.com/project-key: PLEASE
    # jira/project-key: PLEASE
spec:
  type: service
  lifecycle: unknown
  owner: guests
